name: "samtools_pipeline"
description: custom bash pipeline made only of samtools commands
keywords:
  - pipeline
  - bam
  - sam
  - cram
tools:
  - "samtools":
      description: "Tools for dealing with SAM, BAM and CRAM files"
      homepage: "http://www.htslib.org"
      documentation: "https://www.htslib.org/doc/samtools.html"
      tool_dev_url: "https://github.com/samtools/samtools"
      doi: "10.1093/bioinformatics/btp352"
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - input:
      type: file
      description: BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"
  - meta2:
      type: map
      description: |
        Groovy Map containing reference information
        e.g. [ id:'test' ]
  - fasta:
      type: file
      description: FASTA reference file
      pattern: "*.{fasta,fa}"
  - commands:
      type: list
      description: |
        List of the samtools command names to run (in order). Currently
        supported: addreplacerg, collate, fixmate, markdup, reheader, sort,
        view
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - output:
      type: file
      description: Output BAM/CRAM/SAM file (defaults to the same extension as the input)
      pattern: "*.{bam,cram,sam}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@muffato"
maintainers:
  - "@muffato"
