name: "samtools_pipeline"
description: custom bash pipeline made of samtools commands
keywords:
  - pipeline
  - bam
  - sam
  - cram
tools:
  - "samtools":
      description: "Tools for dealing with SAM, BAM and CRAM files"
      homepage: "http://www.htslib.org"
      documentation: "https://www.htslib.org/doc/samtools.html"
      tool_dev_url: "https://github.com/samtools/samtools"
      doi: "10.1093/bioinformatics/btp352"
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - input:
      type: file
      description: BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"
  - meta2:
      type: map
      description: |
        Groovy Map containing reference information
        e.g. [ id:'test' ]
  - fasta:
      type: file
      description: FASTA reference file
      pattern: "*.{fasta,fa}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bam:
      type: file
      description: optional output BAM file
      pattern: "*.{bam}"
  - cram:
      type: file
      description: optional output BAM file
      pattern: "*.{cram}"
  - sam:
      type: file
      description: optional output BAM file
      pattern: "*.{sam}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - output:
      type: file
      description: Collated BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"
authors:
  - "@muffato"
maintainers:
  - "@muffato"
